version: '3.4'

services:
  #kafka_deploy:
  #  image: "kafka_deploy:v0"
  #  ports:
  #    - "8006:8006"
  #    - "9092:9092"
  #    - "2181:2181"
  #  network_mode: "host"

  redis_deploy:
    image: "redis1804:v0"
    ports:
      - "6379:6379"

  streamer_deploy: 
    image: "streamer:v0"
    ports:
      - "8001:8001"
    network_mode: "host"
    volumes:
      - /media/qoala/New Volume3/docker_kubernetes/docker_example/video_streaming/streamer:/home
    depends_on:
      #- "kafka_deploy"
      - "redis_deploy"

  broadcaster_deploy:
    image: "broadcaster2:v0"
    ports:
      - "8005:8005"
    network_mode: "host"
    depends_on:
      #- "kafka_deploy"
      - "redis_deploy"
      - "streamer_deploy"
    volumes:
      - /media/qoala/New Volume3/docker_kubernetes/docker_example/video_streaming/broadcaster:/home
