version: '2.3'

services:
  kafka_deploy:
    image: "kafka_deploy:v0"
    ports:
      - "8006:8006"
      - "9092:9092"
      - "2181:2181"
    network_mode: "host"
    mem_limit: 2000000000

  redis_deploy:
    image: "redis1804:v0"
    ports:
      - "6379:6379"
    depends_on:
      - "kafka_deploy"

  cloud_handler_deploy:
    image: "cloud_handler:v0"
    ports:
      - "8004:8004"
    network_mode: "host"
    depends_on:
      - "kafka_deploy"
      - "redis_deploy"
    volumes:
      - /media/qoala/New Volume3/docker_kubernetes/docker_example/video_streaming/cloud_handler:/home

  web_deploy:
    image: "web:v0"
    ports:
      - "8080:8080"
    network_mode: "host"
    depends_on:
      - "kafka_deploy"
      - "redis_deploy"
      - "cloud_handler_deploy"
    volumes:
      - /media/qoala/New Volume3/ivb-pertamina:/home

  streamer_deploy: 
    image: "streamer:v0"
    ports:
      - "8001:8001"
    network_mode: "host"
    volumes:
      - /media/qoala/New Volume3/docker_kubernetes/docker_example/video_streaming/streamer:/home
    depends_on:
      - "kafka_deploy"
      - "redis_deploy"
      - "cloud_handler_deploy"
      - "web_deploy"

  ai_deploy: 
    image: "ai:v0"
    runtime: nvidia
    ports:
      - "8002:8002"
    network_mode: "host"
    volumes:
      - /media/qoala/New Volume3/docker_kubernetes/docker_example/video_streaming/ai:/home
    depends_on:
      - "kafka_deploy"
      - "redis_deploy"
      - "cloud_handler_deploy"
      - "streamer_deploy"

  visualizer_deploy: 
    image: "visualizer:v0"
    ports:
      - "8003:8003"
    network_mode: "host"
    volumes:
      - /media/qoala/New Volume3/docker_kubernetes/docker_example/video_streaming/visualizer:/home
    depends_on:
      - "kafka_deploy"
      - "redis_deploy"
      - "streamer_deploy"
      - "ai_deploy"

  saver_deploy: 
    image: "saver:v0"
    ports:
      - "8006:8006"
    network_mode: "host"
    volumes:
      - /media/qoala/New Volume3/docker_kubernetes/docker_example/video_streaming/saver:/home
    depends_on:
      - "kafka_deploy"
      - "redis_deploy"
      - "streamer_deploy"
      - "ai_deploy"

  broadcaster_deploy:
    image: "broadcaster2:v0"
    ports:
      - "8005:8005"
    network_mode: "host"
    depends_on:
      - "kafka_deploy"
      - "redis_deploy"
      - "streamer_deploy"
      - "visualizer_deploy"
    volumes:
      - /media/qoala/New Volume3/docker_kubernetes/docker_example/video_streaming/broadcaster:/home

